import Head from "next/head";
import NavBar from "../components/NavBar.js";
import { useEffect } from "react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    
     
      <NavBar />

      <div
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          textAlign: "center",
          backgroundColor: "black",
          fontFamily: "Arial, sans-serif",
        }}
      >
        <h1 style={{ fontSize: "3rem", margin: 0, color: "white" }}>
          Site will be ready soon!
        </h1>
      </div>
    </>
  );
}
